services:
  data_store:
    build:
      context: .
      dockerfile: data_config/Dockerfile
    env_file: "/opt/wtx_viewer/app_credentials.env"

  viewer_app:
    build:
      context: .
      dockerfile: server_config/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - data_store