server {
    listen 80;
    server_name _;

    location /data/zarr/ {
        proxy_pass ${SWIFT_STORAGE_URL}/main/mosaic.zarr/;
        proxy_set_header X-Auth-Token "${SWIFT_AUTH_TOKEN}";
        proxy_set_header Host object-store.rc.nectar.org.au;
        proxy_hide_header X-Trans-Id;

        add_header Access-Control-Allow-Origin  "*"                                             always;
        add_header Access-Control-Allow-Methods "GET, OPTIONS, HEAD"                            always;
        add_header Access-Control-Allow-Headers "Range, Content-Type"                           always;
        add_header Access-Control-Expose-Headers "Content-Range, Content-Length, Accept-Ranges" always;

        if ($request_method = OPTIONS) {
            add_header Access-Control-Allow-Origin  "*";
            add_header Access-Control-Allow-Methods "GET, OPTIONS, HEAD";
            add_header Access-Control-Allow-Headers "Range, Content-Type";
            add_header Content-Length 0;
            return 204;
        }

        types {
            application/json     json zattrs zgroup zarray zmetadata;
            application/octet-stream bin;
        }
        default_type application/octet-stream;
    }
}
