FROM nginx:alpine

COPY server_config/index.html /usr/share/nginx/html/index.html
COPY server_config/nginx.conf /etc/nginx/conf.d/default.conf
COPY vitessce_config/config.json /usr/share/nginx/html/config.json