# define backend to data_store service
upstream data_store {
    server data_store;
    keepalive 32;
}

# redirect all HTTP to HTTPS
server {
    listen 80;
    server_name viewer.nsclc-spatial-atlas.cloud.edu.au;
    return 301 https://$host$request_uri;
}

# https
server {
    listen 443 ssl;
    server_name viewer.nsclc-spatial-atlas.cloud.edu.au;

    # load ssl certificates from cloud init
    ssl_certificate /etc/letsencrypt/live/viewer.nsclc-spatial-atlas.cloud.edu.au/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/viewer.nsclc-spatial-atlas.cloud.edu.au/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384;
    ssl_prefer_server_ciphers off;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 1d;

    root  /usr/share/nginx/html;
    index index.html; # serves react/vitessce app component

    # dont cache
    location = /config.json {
        add_header Cache-Control "no-store, no-cache, must-revalidate";
        try_files $uri =404;
    }


    location /zarr/ {
        proxy_pass http://data_store/data/zarr/;

        # for upstream data_store keepalive
        proxy_http_version 1.1;
        proxy_set_header Connection "";

        add_header Access-Control-Allow-Origin "*" always;
        add_header Access-Control-Allow-Methods "GET, OPTIONS, HEAD" always; #readonly
        add_header Access-Control-Allow-Headers "Range, Content-Type" always;
        add_header Access-Control-Expose-Headers "Content-Range, Content-Length, Accept-Ranges" always;

        if ($request_method = OPTIONS) {
            add_header Access-Control-Allow-Origin "*";
            add_header Access-Control-Allow-Methods "GET, OPTIONS, HEAD";
            add_header Access-Control-Allow-Headers "Range, Content-Type";
            add_header Content-Length 0;
            return 204;
        }
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
