# OpenStack instance configuration for wtx-viewer deployment

instance:
  name: wtx-viewer
  image: "NeCTAR Ubuntu 22.04 LTS (Jammy) amd64 (with Docker)"
  flavor: m3.small # adjust later 
  network: QRIScloud
  security_groups: [default, ssh, viewer_ingress]
  key_name: "fimac2" # NOTE: delete once SSH no longer needed for debugging.
  github_actions_key: "github-actions-update" # name of the action runner for updating repo instance + service

app:
  target_zone: "nsclc-spatial-atlas.cloud.edu.au."
  app_domain:  "viewer.nsclc-spatial-atlas.cloud.edu.au."
  ttl: 300
  admin_email: "admin@nsclc-spatial-atlas.cloud.edu.au"
