name: CD

on:
  # auto-triggers after CI passes on main
  workflow_run:
    workflows: ["CI"]
    types: [completed]
    branches: [main]
  workflow_dispatch:  # enable manual trigger

jobs:
  production:
    uses: ./.github/workflows/deploy.yml
    with:
      environment: production
    secrets: inherit
