name: Start Nectar VM

# manual trigger only
on:
  workflow_dispatch:

jobs:
  provision:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Run deploy.py
        working-directory: ardcnectar
        env:
          OS_AUTH_URL:                       ${{ secrets.OS_AUTH_URL }}
          OS_APPLICATION_CREDENTIAL_ID:      ${{ secrets.OS_APPLICATION_CREDENTIAL_ID }}
          OS_APPLICATION_CREDENTIAL_SECRET:  ${{ secrets.OS_APPLICATION_CREDENTIAL_SECRET }}
        run: uv run deploy.py
